export const POPULAR_LEAGUES = [
  "English Premier League",
  "Spanish La Liga",
  "Italian Serie A",
  "German Bundesliga",
  "French Ligue 1",
];

export const POPULAR_TEAMS = {
  "English Premier League": [
    "Arsenal",
    "Chelsea",
    "Liverpool",
    "Manchester City",
    "Manchester United",
    "Tottenham",
    "Newcastle",
    "Everton",
    "Aston Villa",
    "Leeds",
  ],
  "Spanish La Liga": [
    "Real Madrid",
    "Barcelona",
    "Atl\u00e9tico Madrid",
    "Sevilla",
    "Valencia",
    "Villarreal",
    "Real Sociedad",
    "Athletic Bilbao",
    "Real Betis",
    "Celta Vigo",
  ],
  "Italian Serie A": [
    "Juventus",
    "AC Milan",
    "Inter",
    "Roma",
    "Lazio",
    "Napoli",
    "Fiorentina",
    "Atalanta",
    "Torino",
    "Sampdoria",
  ],
  "German Bundesliga": [
    "Bayern Munich",
    "Borussia Dortmund",
    "RB Leipzig",
    "Bayer Leverkusen",
    "Schalke 04",
    "VfL Wolfsburg",
    "Borussia M\u00f6nchengladbach",
    "Eintracht Frankfurt",
    "Hertha Berlin",
    "Werder Bremen",
  ],
  "French Ligue 1": [
    "Paris Saint-Germain",
    "Marseille",
    "Lyon",
    "Monaco",
    "Lille",
    "Nice",
    "Rennes",
    "Bordeaux",
    "Saint-\u00c9tienne",
    "Nantes",
  ],
};

export const NATIONALITIES = [
  "Brazil",
  "Spain",
  "Italy",
  "France",
  "Germany",
  "Argentina",
  "Portugal",
  "The Netherlands",
  "England",
  "Belgium",
  "Croatia",
  "Uruguay",
  "Mexico",
  "United States",
  "Japan",
  "South Korea",
];

export const DEFAULT_TEAMS = Object.values(POPULAR_TEAMS).flat();
